{"name": "Admin user not Logged in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text : \nMessage: unexpected alert open: {Alert text : }\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x00BAB793+45827]\n\t(No symbol) [0x00B3DB74]\n\t(No symbol) [0x00A3150F]\n\t(No symbol) [0x00AAC616]\n\t(No symbol) [0x00A92B96]\n\t(No symbol) [0x00A66998]\n\t(No symbol) [0x00A6751D]\n\tGetHandleVerifier [0x00E643C3+2899763]\n\tGetHandleVerifier [0x00EB77ED+3240797]\n\tGetHandleVerifier [0x00C31264+593364]\n\tGetHandleVerifier [0x00C3818C+621820]\n\t(No symbol) [0x00B46F54]\n\t(No symbol) [0x00B43658]\n\t(No symbol) [0x00B437F7]\n\t(No symbol) [0x00B358AE]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 39, in login\n    fwu_login_functions.cancel_popup(context.driver, fwu_login_elements.button_cancel_id)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\Functions\\fwu_login_functions.py\", line 13, in cancel_popup\n    driver.find_element('id', fwu_login_elements.button_cancel_id).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 228, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "When user tries to login with invalid credential", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text : \nMessage: unexpected alert open: {Alert text : }\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x00BAB793+45827]\n\t(No symbol) [0x00B3DB74]\n\t(No symbol) [0x00A3150F]\n\t(No symbol) [0x00AAC616]\n\t(No symbol) [0x00A92B96]\n\t(No symbol) [0x00A66998]\n\t(No symbol) [0x00A6751D]\n\tGetHandleVerifier [0x00E643C3+2899763]\n\tGetHandleVerifier [0x00EB77ED+3240797]\n\tGetHandleVerifier [0x00C31264+593364]\n\tGetHandleVerifier [0x00C3818C+621820]\n\t(No symbol) [0x00B46F54]\n\t(No symbol) [0x00B43658]\n\t(No symbol) [0x00B437F7]\n\t(No symbol) [0x00B358AE]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 39, in login\n    fwu_login_functions.cancel_popup(context.driver, fwu_login_elements.button_cancel_id)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\Functions\\fwu_login_functions.py\", line 13, in cancel_popup\n    driver.find_element('id', fwu_login_elements.button_cancel_id).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 228, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1716375207748, "stop": 1716375207777}, {"name": "Then user should not be logged in", "status": "skipped", "start": 1716375207778, "stop": 1716375207778}], "start": 1716375207747, "stop": 1716375207778, "uuid": "8ba18cd0-dd32-4bc5-9c24-44b592de4e65", "historyId": "6c61cc824d7d6039b43482224b06117d", "fullName": "User login: Admin user not Logged in", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "invalidcred"}, {"name": "feature", "value": "User login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}