{"name": "Admin user Login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text : \nMessage: unexpected alert open: {Alert text : }\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x00B2B793+45827]\n\t(No symbol) [0x00ABDB74]\n\t(No symbol) [0x009B150F]\n\t(No symbol) [0x00A2C616]\n\t(No symbol) [0x00A12B96]\n\t(No symbol) [0x009E6998]\n\t(No symbol) [0x009E751D]\n\tGetHandleVerifier [0x00DE43C3+2899763]\n\tGetHandleVerifier [0x00E377ED+3240797]\n\tGetHandleVerifier [0x00BB1264+593364]\n\tGetHandleVerifier [0x00BB818C+621820]\n\t(No symbol) [0x00AC6F54]\n\t(No symbol) [0x00AC3658]\n\t(No symbol) [0x00AC37F7]\n\t(No symbol) [0x00AB58AE]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 25, in login\n    fwu_login_functions.cancel_message(context.driver, fwu_login_elements.button_cancel_message)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\Functions\\fwu_login_functions.py\", line 28, in cancel_message\n    driver.find_element('id', fwu_login_elements.button_cancel_message).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 228, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "When user logged in with valid credential", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text : \nMessage: unexpected alert open: {Alert text : }\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x00B2B793+45827]\n\t(No symbol) [0x00ABDB74]\n\t(No symbol) [0x009B150F]\n\t(No symbol) [0x00A2C616]\n\t(No symbol) [0x00A12B96]\n\t(No symbol) [0x009E6998]\n\t(No symbol) [0x009E751D]\n\tGetHandleVerifier [0x00DE43C3+2899763]\n\tGetHandleVerifier [0x00E377ED+3240797]\n\tGetHandleVerifier [0x00BB1264+593364]\n\tGetHandleVerifier [0x00BB818C+621820]\n\t(No symbol) [0x00AC6F54]\n\t(No symbol) [0x00AC3658]\n\t(No symbol) [0x00AC37F7]\n\t(No symbol) [0x00AB58AE]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 25, in login\n    fwu_login_functions.cancel_message(context.driver, fwu_login_elements.button_cancel_message)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\Functions\\fwu_login_functions.py\", line 28, in cancel_message\n    driver.find_element('id', fwu_login_elements.button_cancel_message).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 228, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1716371186763, "stop": 1716371194733}, {"name": "Then user should be logged out successfully", "status": "skipped", "start": 1716371194735, "stop": 1716371194735}], "start": 1716371186762, "stop": 1716371194735, "uuid": "ecc4a543-9482-4e60-92fc-6a998f1d5f46", "historyId": "e3e7f1721e504f6b1c5a653a6a85665c", "fullName": "User login: Admin user Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "validcred"}, {"name": "feature", "value": "User login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}