{"name": "Admin user Login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoAlertPresentException: Message: no such alert\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x003E0B13+45059]\n\t(No symbol) [0x003768A4]\n\t(No symbol) [0x0027137D]\n\t(No symbol) [0x002630A4]\n\t(No symbol) [0x0028DCF9]\n\t(No symbol) [0x002D2DF4]\n\t(No symbol) [0x0028DB51]\n\t(No symbol) [0x002D2AF6]\n\t(No symbol) [0x002A6948]\n\t(No symbol) [0x002A74CD]\n\tGetHandleVerifier [0x0069F9A3+2924179]\n\tGetHandleVerifier [0x006F36ED+3267549]\n\tGetHandleVerifier [0x00464474+584036]\n\tGetHandleVerifier [0x0046B1DC+612044]\n\t(No symbol) [0x0037FAB4]\n\t(No symbol) [0x0037C358]\n\t(No symbol) [0x0037C4F7]\n\t(No symbol) [0x0036E46E]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 22, in login\n    context.driver.switch_to.alert.dismiss()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\switch_to.py\", line 58, in alert\n    _ = alert.text\n        ^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\alert.py\", line 58, in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "When user logged in with valid credential", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoAlertPresentException: Message: no such alert\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x003E0B13+45059]\n\t(No symbol) [0x003768A4]\n\t(No symbol) [0x0027137D]\n\t(No symbol) [0x002630A4]\n\t(No symbol) [0x0028DCF9]\n\t(No symbol) [0x002D2DF4]\n\t(No symbol) [0x0028DB51]\n\t(No symbol) [0x002D2AF6]\n\t(No symbol) [0x002A6948]\n\t(No symbol) [0x002A74CD]\n\tGetHandleVerifier [0x0069F9A3+2924179]\n\tGetHandleVerifier [0x006F36ED+3267549]\n\tGetHandleVerifier [0x00464474+584036]\n\tGetHandleVerifier [0x0046B1DC+612044]\n\t(No symbol) [0x0037FAB4]\n\t(No symbol) [0x0037C358]\n\t(No symbol) [0x0037C4F7]\n\t(No symbol) [0x0036E46E]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 22, in login\n    context.driver.switch_to.alert.dismiss()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\switch_to.py\", line 58, in alert\n    _ = alert.text\n        ^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\alert.py\", line 58, in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1716191586411, "stop": 1716191596802}, {"name": "Then user should be logged in successfully", "status": "skipped", "start": 1716191596805, "stop": 1716191596805}], "start": 1716191586409, "stop": 1716191596805, "uuid": "8f3ce65a-a99a-400f-b89c-18f32256bc40", "historyId": "e3e7f1721e504f6b1c5a653a6a85665c", "fullName": "User login: Admin user Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "validcred"}, {"name": "feature", "value": "User login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}