{"name": "Admin user Login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoAlertPresentException: Message: no such alert\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x00ACB793+45827]\n\t(No symbol) [0x00A5DB74]\n\t(No symbol) [0x0095138D]\n\t(No symbol) [0x009430A4]\n\t(No symbol) [0x0096DD09]\n\t(No symbol) [0x009B2E94]\n\t(No symbol) [0x0096DB61]\n\t(No symbol) [0x009B2B96]\n\t(No symbol) [0x00986998]\n\t(No symbol) [0x0098751D]\n\tGetHandleVerifier [0x00D843C3+2899763]\n\tGetHandleVerifier [0x00DD77ED+3240797]\n\tGetHandleVerifier [0x00B51264+593364]\n\tGetHandleVerifier [0x00B5818C+621820]\n\t(No symbol) [0x00A66F54]\n\t(No symbol) [0x00A63658]\n\t(No symbol) [0x00A637F7]\n\t(No symbol) [0x00A558AE]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 22, in login\n    context.driver.switch_to.alert.dismiss()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\switch_to.py\", line 58, in alert\n    _ = alert.text\n        ^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\alert.py\", line 58, in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "When user logged in with valid credential", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoAlertPresentException: Message: no such alert\n  (Session info: chrome=125.0.6422.60)\nStacktrace:\n\tGetHandleVerifier [0x00ACB793+45827]\n\t(No symbol) [0x00A5DB74]\n\t(No symbol) [0x0095138D]\n\t(No symbol) [0x009430A4]\n\t(No symbol) [0x0096DD09]\n\t(No symbol) [0x009B2E94]\n\t(No symbol) [0x0096DB61]\n\t(No symbol) [0x009B2B96]\n\t(No symbol) [0x00986998]\n\t(No symbol) [0x0098751D]\n\tGetHandleVerifier [0x00D843C3+2899763]\n\tGetHandleVerifier [0x00DD77ED+3240797]\n\tGetHandleVerifier [0x00B51264+593364]\n\tGetHandleVerifier [0x00B5818C+621820]\n\t(No symbol) [0x00A66F54]\n\t(No symbol) [0x00A63658]\n\t(No symbol) [0x00A637F7]\n\t(No symbol) [0x00A558AE]\n\tBaseThreadInitThunk [0x777CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x779175F4+228]\n\tRtlGetAppContainerNamedObjectPath [0x779175C4+180]\n\n", "trace": "  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test.py\", line 22, in login\n    context.driver.switch_to.alert.dismiss()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\switch_to.py\", line 58, in alert\n    _ = alert.text\n        ^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\alert.py\", line 58, in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akbar.raza\\PycharmProjects\\FWU\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1716364543459, "stop": 1716364546327}, {"name": "Then user should be logged in successfully", "status": "skipped", "start": 1716364546328, "stop": 1716364546328}], "start": 1716364543457, "stop": 1716364546328, "uuid": "5e102357-e305-44ca-84a4-54d83b61bf4e", "historyId": "e3e7f1721e504f6b1c5a653a6a85665c", "fullName": "User login: Admin user Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "validcred"}, {"name": "feature", "value": "User login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}